import Head from 'next/head'
import Avatar from '../components/Avatar'
import { ViewGridIcon } from '@heroicons/react/solid'


export default function Home() {
  return (
   <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
  
      </Head>




<header className="flex w-full p-5 justify-end text-sm text-gray-700">

<div className="flex ">
<ul className="flex space-x-4 items-center  ">
  <li><a className="link" >Gmail</a></li>
  <li><a className="link">Images</a></li>
  <ViewGridIcon className="h-10
   w-10 
   p-2
   hover:bg-gray-100 rounded-full"/> 

<Avatar url="https://lh3.googleusercontent.com/a-/AFdZucr8FsQ21ozIQjjZnCLPMW_eed7hypWYvtsdXVAOjxw=s288-p-rw-no"/>


</ul>
</div>


</header>



    </div>
  )
}
